name: Deploy to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-southeast-2
  ECR_REGISTRY: 601102828184.dkr.ecr.ap-southeast-2.amazonaws.com

jobs:
  build-and-push:
    name: Build and Push Images to ECR
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Kéo code từ GitHub về máy chủ ảo
    - name: Checkout code
      uses: actions/checkout@v4

    # Bước 2: Đăng nhập vào AWS sử dụng Secrets đã cấu hình
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Bước 3: Build và Push Image Frontend
    - name: Build, tag, and push Frontend image
      run: |
        docker build -t ${{ env.ECR_REGISTRY }}/aqi-frontend:latest ./frontend
        docker push ${{ env.ECR_REGISTRY }}/aqi-frontend:latest

    # Bước 4: Build và Push Image Backend
    - name: Build, tag, and push Backend image
      run: |
        docker build -t ${{ env.ECR_REGISTRY }}/aqi-backend:latest ./backend
        docker push ${{ env.ECR_REGISTRY }}/aqi-backend:latest
